- .hound.yml
- package.json
- This PR integrates HoundCI with the repository
- We need to integrate Hound CI for Pull request code review. It checks against code semantics and style violations. This allows us to maintain a clean codebase.
[#166172740](https://www.pivotaltracker.com/story/show/166172740)
> #166172740 Integrate repository with HoundCI

- .prettierrc.js
- package-lock.json
- package.json
Add Prettier Pre-Commit Hook
We want to add a pre-commit hook that runs prettier against code to be committed. This would ensure that when on our syntax rules is violated, a commit won't be possible.
* Confirm that you have `prettier pre-commit` and `husky` installed in your editor
* Checkout to this branch with `git checkout chore/166196092/setup-pre-commit-hook`
* Deliberately violate a syntax rule and try to commit the file.
* Confirm that  your commit is not possible
#166196092
> #166196092 Setup prettier pre-commit hook

- src/database/models/averageRating.js
- src/database/models/language.js
- src/database/models/languageStack.js
- src/database/models/proficiency.js
- src/database/models/rating.js
- src/database/models/resource.js
- src/database/models/review.js
- src/database/models/stack.js
- src/database/models/subtopic.js
- src/database/models/topic.js
- src/database/models/user.js
- Changes the primary key `type` to `UUID`
- Adds `defaultValue` of `uuidv4` to our primary keys
- We need to ensure that the primary keys (ids) are unique. Let's use type: DataTypes.UUID and also give our primary keys a default value of uuidv4.
- Verify that the `ids` in the model files are of type `UUID` and have a default value of `UUIDV4`
[#166258324](https://www.pivotaltracker.com/story/show/166258324)
> #166258324 Use uuid as primary key

- package-lock.json
- package.json
- server.js
Uses consola to log server run status
To ensure that upon a successful start of our app, our user gets a console message with `Find me on port ${port}`.
Type `npm run dev` in the terminal and you should be able to see the console message.
#166264853
> #166264853 Use consola to log server run status

- .travis.yml
- package.json
- travis.yml
- Sets up Travis Ci for our codebase
-  Setup Travis CI for Continuous Integration
-  Create a` travis.yml` file.
[#166172698](https://www.pivotaltracker.com/story/show/166172698)
>  #166172698 Setup Travis-CI

- package.json
-fix sequelize security issue
- update version of sequelise in the package.json file
- you can test this by checking if github still gives this warning
**#166384533**
> #166384533 fix sequelize security issue

- src/database/migrations/001-create-user.js
- src/database/migrations/002-create-stack.js
- src/database/migrations/003-create-language.js
- src/database/migrations/004-create-language-stack.js
- src/database/migrations/005-create-topic.js
- src/database/migrations/006-create-subtopic.js
- src/database/migrations/007-create-resource.js
- src/database/migrations/008-create-rating.js
- src/database/migrations/009-create-averageRating.js
- src/database/migrations/010-create-review.js
- src/database/migrations/011-create-proficiency.js
- adds timeStamp columns for migration files
- add column for `createdAt`
- add column for `updatedAt`
[#166394771](https://www.pivotaltracker.com/story/show/166394771)
> #166394771 Add timeStamp columns

- .codeclimate.yml
- README.md
Add setup for code climate and badges
Add codeclimate Setup
[#166325823](https://www.pivotaltracker.com/story/show/166325823)
> Add code climate setup

- .eslintrc
- .gitignore
- package.json
- src/app/user/controllers/createUser.js
- src/app/user/middleware/index.js
- src/app/user/routes/index.js
- src/common/helpers/index.js
- src/common/helpers/paramValidator.js
- src/common/index.js
- adds validator for input type
- adds validator for required fields
- adds build and start scripts to package.json
- We need to add param validators for our inputs to ensure that our database only receives valid params.
- send a `POST` request to `/users/auth/signup` with invalid param types or without required params
- confirm that you receive adequate error messages respectively.
[#166394897](https://www.pivotaltracker.com/story/show/166394897)
> #166394897 Add param validator

- src/app/user/controllers/createUser.js
- src/app/user/middleware/index.js
- src/app/user/routes/index.js
- src/common/helpers/index.js
- src/common/helpers/paramValidator.js
- src/common/index.js
- adds a unique `param` validator
- adds middleware for `uniqueEmail` and `uniqueUsername` to the user route
- add a unique param validator for enforcing unique constraints on our unique model columns.
- send a `POST` request to `/user/auth/signup` with required params and already existing unique params --like a `username` that already exists in the `db`.
- You should receive an error message informing you that the `param` already exists.
[#166396585](https://www.pivotaltracker.com/story/show/166396585)
>  #166396585 Add unique param validator

- docs/api.js
- docs/index.js
- package.json
- src/index.js
Setups Swagger for API documentation.
We need to document our API so that contributors can understand how to use it effectively.
* Run `npm run dev` in the terminal.
* Go to `localhost:3000/api/v1/docs (Change port number if your server is running on a different port)
#166276522
> #166276522 setup swagger

- package.json
- add coverage script for `travis ci` to` package.json`
- update `package.json` with the `coverage script`
- check if the the `coverage` in the github repo is updated after each successful `run test`
[#166467420](https://www.pivotaltracker.com/story/show/166467420)
> #166467420 Add Coverage Script To `package.json`

- .codeclimate.yml
- src/app/user/_tests_/user.spec.js
- src/common/helpers/paramValidator.js
- src/common/index.js
- src/common/middleware/authentication.js
- src/common/middleware/index.js
- src/database/models/averageRating.js
- src/database/models/languageStack.js
- src/index.js
- adds authentication.js middleware
- refactors uniqueParamValidator
- adds tests for user module
- the authentication middleware will be tested when we implement protected routes
- for the tests, confirm that the user module files are now covered
[#166473183](https://www.pivotaltracker.com/story/show/166473183)
> #166473183 Add auth functionality

- src/app/index.js
- src/app/technology/_tests_/technology.spec.js
- src/app/technology/controller.js
- src/app/technology/index.js
- src/app/technology/middleware.js
- src/app/technology/routes.js
- src/common/helpers/index.js
- src/common/helpers/paramValidator.js
- src/common/index.js
- src/index.js
- It allows an admin or super admin to add new technology to an existing category
- add technology-create functionality
- write tests 
- hit `POST /technologies` with `name` and `category` params
- ensure you are an admin
- ensure `category` exists
[#166611674](https://app.asana.com/0/1124070829248768/1126633028744961/f)
> #166611674 Add technology create functionality

- src/database/migrations/004-create-topic.js
- src/database/models/technology.js
- src/database/models/topic.js
- changes `technologyId` field to `technology`
- makes `name` field in `technology` model primary key
- adds a `hasMany` association to technology
- We need to refactor the topic model file so that instead of the technologyId field, we have a technology field. This would make our API easier to use, since the name field is unique.
[#166634559](https://www.pivotaltracker.com/story/show/166634559)
> #166634559 Refactor topic model

- src/app/index.js
- src/app/topic/_tests_/topic.spec.js
- src/app/topic/controller.js
- src/app/topic/index.js
- src/app/topic/middleware.js
- src/app/topic/routes.js
- src/common/helpers/index.js
- src/common/helpers/paramValidator.js
- src/common/index.js
- src/database/models/proficiency.js
- src/database/models/resource.js
- src/database/models/topic.js
- src/index.js
request body: 
```
name: name
technology: technology
```
[#166634378](https://www.pivotaltracker.com/story/show/166634378)
> #166634378 Add topic to technology

- src/app/index.js
- src/app/proficiency/_tests_/proficiency.spec.js
- src/app/proficiency/controller.js
- src/app/proficiency/index.js
- src/app/proficiency/middleware.js
- src/app/proficiency/routes.js
- src/app/rating/controller.js
- src/app/technology/controller.js
- src/app/technology/routes.js
- src/common/index.js
- src/common/middleware/authentication.js
- src/common/middleware/index.js
- src/database/migrations/010-create-proficiency.js
- src/database/models/proficiency.js
- src/database/models/topic.js
- src/index.js
- adds complete topic controller
- adds complete subtopic controller
- adds middleware for proficiency
- adds routes for proficiency
- refactors topic-proficiency association
- adds `subtopicIds` column to proficiency table
- adds `getUserId` middleware in authentication file
- includes proficiency for GetTechnologies
- Users need to be able to track their proficiency for topics. This feature enables a user to successfully complete a subtopic and a topic.
- Run `db:roll:migrate`
- Send a `POST` request to `/api/v1/proficiencies/subtopic` with body param `subtopicId` to mark a subtopic as completed
- Send a `POST` request to `/api/v1/proficiencies/topic` with body param `topicId` to mark a topic as completed
- When a user completes a subtopic, it updates his/ her proficiency level for that …
> #166723643 subtopic - topic completion

- src/app/topic/_tests_/topic.spec.js
- src/app/topic/controller.js
- src/app/topic/middleware.js
- src/database/migrations/004-create-topic.js
- src/database/seeders/004-default-topics.js
request body: 
```
name: ['name1', 'name2'] or name
technology: technology
```
[#166697074](https://www.pivotaltracker.com/story/show/166697074)
> 166697074 Create multiple topics

- src/app/topic/middleware.js
- src/app/user/_tests_/user.spec.js
- src/app/user/controller.js
- src/app/user/middleware.js
- src/app/user/routes.js
- adds controller for updateRole
- adds middleware for updateRole
- adds route for updateRole
- refactors error message in `isNameUniqueForTechnology` controller
- This feature enables an admin to update a user's role.
- Send a `PATCH` request to `/api/v1/users/role` with params:
```
userId: <valid user id>,
role: <one of [admin, expert, editor, user]
```
- You should receive a success message if your inputs are valid
N/A
[#166759204](https://www.pivotaltracker.com/story/show/166759204)
> #166759204 Implement update role feature

- src/app/user/_tests_/user.spec.js
- src/app/user/controller.js
- src/app/user/middleware.js
- src/app/user/routes.js
* adds controller for updating user details
* adds middleware for updating user details
* adds route for updating user details
* adds tests for updating user details
Allows users to update their details through a PATCH request.
- Send a `PATCH` request to `/api/v1/users/update` with params:
```
firstName: <first name>,
lastName: <last name>,
```
- You should receive a success message if your inputs and token is valid
[#166486702](https://www.pivotaltracker.com/story/show/)
> Update User Details

- src/app/category/_tests_/category.spec.js
- src/app/category/controller.js
Write unit tests for the category routes
- create a new sub folder in `category` with name `_test_`
- create a file with name `category.spec.js`
- write tests for the category routes
in your terminal try `npm run test` and see if the tests are passing
[#166719067](https://www.pivotaltracker.com/story/show/)
> #166719067 Write unit tests for the category routes

- .codeclimate.yml
- .env.example
- docs/api.js
- src/app/proficiency/controller.js
- generates API documentation with postman
- edits `docs/api.js` to host API documentation with swagger
- edits the `completeTopic` function in `src/app/profiency/controller.js`
- adds env BASE_URL variable
- added `docs` to `.codeclimate.yml`
We need documentation for our API.
* run `npm run dev`
* go to `api/v1/docs`
[#167066158](https://www.pivotaltracker.com/story/show/)
> Generate Api Documentation with PostMan

- src/app/resource/controller.js
- src/app/technology/controller.js
- src/database/models/subtopic.js
This PR implements adjustments for the web app functionality:
- includes topic model in getResources controller
- includes subtopic and resources models in getTechnologies controller
- adds subtopic-resource association in subtopic model file
> Include topic and proficiency models in getCategories controller

- src/app/category/controller.js
- This PR includes the resource model in the getCategories controller
> Include resources in the getCategories controller
